# Generated by Django 3.1.2 on 2020-10-05 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_price'),
        ('price', '0004_auto_20201005_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='product.product'),
            preserve_default=False,
        ),
    ]
