# Generated by Django 3.1.2 on 2020-10-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_auto_20201005_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
        migrations.AlterField(
            model_name='productprice',
            name='amount',
            field=models.FloatField(),
        ),
    ]
