# Generated by Django 3.1.2 on 2020-10-05 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_auto_20201003_1802'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.region'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
