# Generated by Django 3.1.2 on 2020-10-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_document'),
        ('reference', '0003_city'),
        ('company', '0005_auto_20201005_1434'),
        ('document', '0003_auto_20201007_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainInfo',
            new_name='Info',
        ),
    ]
