# Generated by Django 3.1.2 on 2020-10-05 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20201005_1218'),
        ('customer', '0002_auto_20201005_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='document.maininfo'),
        ),
    ]
