# Generated by Django 3.1.2 on 2020-10-07 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20201005_1218'),
        ('customer', '0004_auto_20201006_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='document.document'),
        ),
    ]
