# Generated by Django 3.1.2 on 2020-10-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20201030_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='case_amount',
            new_name='box_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unit_type',
            new_name='measure',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
