# Generated by Django 3.1.2 on 2020-10-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbox',
            options={'verbose_name_plural': 'cashboxes'},
        ),
    ]
