# Generated by Django 3.1.2 on 2020-10-04 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('UZBEK', "O'zbek"), ('ENGLISH', 'English'), ('RUSSIAN', 'Русский язык')], default='UZBEK', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('USER', 'User'), ('WAREHOUSE_KEEPER', 'Warehouse keeper')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
