# Generated by Django 3.1.2 on 2020-10-07 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20201005_1218'),
        ('erp_user', '0002_auto_20201004_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='document.document'),
        ),
    ]
