# Generated by Django 3.1.2 on 2020-10-07 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20201007_1229'),
        ('erp_user', '0004_auto_20201007_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_user', to='document.document'),
        ),
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_user', to='document.info'),
        ),
    ]
