# Generated by Django 3.1.2 on 2020-10-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='info',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
