# Generated by Django 3.1.2 on 2020-10-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_branch_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'branches'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
    ]
