# Generated by Django 3.1.2 on 2020-10-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20201004_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='status',
        ),
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
