# Generated by Django 3.1.2 on 2020-10-30 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20201007_1229'),
        ('company', '0005_auto_20201005_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='document.info'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
