# Generated by Django 3.1.2 on 2020-10-05 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0006_product_group'),
        ('price', '0007_auto_20201005_1246'),
        ('customer', '0002_auto_20201005_1218'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='price.price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('DRAFT', 'Draft'), ('IN_PROGRESS', 'In progress'), ('WAITING', 'Waiting'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('ARCHIVE', 'Archive')], max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('deliver_date', models.DateTimeField()),
                ('note', models.TextField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customer.customer')),
                ('item', models.ManyToManyField(to='order.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
